### ISSUE TITLE
Configuration files for LSL LabRecorder

### ISSUE THREAD

**Issue by chinmaib** [ml4ai/tomcat#294]
The LSL LabRecorder program which will run on the CAT server needs a configuration file that it can read and then save the data into the corresponding experiment folder.

**Comment by chinmaib** [comment]
The LSL LabRecorder program allows us to specify a configuration file it can use as a command line argument.
Current location of the LabRecorder program on the CAT server: **/usr/LabRecorder**

We can invoke the LabRecorder program to read in a configuration file using the -c option:
Command: **./LabRecorder -c <name_of_the_configuration_file>.cfg**

**Comment by chinmaib** [comment]
However, the program options have some limitations and it does not allow us to read in the system date which is required to specify the experiment folder (exp_yyyy_mm_dd_hh). 
As an alternative, I think we can write a bash script to create a config file (or three, one for lion, tiger, and leopard) for each experiment and invoke the LabRecorder program(s) with the appropriate config file(s). This config file will include the location of the exp folder (exp_yyyy_mm_dd_hh) and the required streams specified. 
I believe this script can be integrated into the Uber script later. @paulosoaresit  let me know what you think.
Once all the required streams are detected, we can even auto start the recording process through scripts which will save us some time.

**Comment by chinmaib** [comment]
Example config file for LabRecorder program:

[General]
StudyRoot=/data/cat/LangLab/experiments/study3_pilot
**PathTemplate=/exp_2022_05_05_10/lion/lion_participant_id.xdf**
RequiredStreams={Aurora (lion), pupil_capture (lion)}
RCSEnabled=1
RCSPort=22345
~

**Comment by adarshp** [comment]
TODO: Check in the templates from CAT into the ml4ai/tomcat repository.

**Comment by rchamplin** [comment]
I created LabRecorder config file and created script to start LabRecorder instances on CAT and start the recording for Lion, Tiger and Leopard's LSL streams. My new scripts will be tested in dry run session 8/2/22.

**Comment by CalebUAz** [comment]
This is fixed!

**Comment by adarshp** [comment]
@CalebUAz - not fixed until the config files are in the repo :)

**Comment by CalebUAz** [comment]
@rchamplin can you push the config files onto the ToMCAT repo?

**Comment by CalebUAz** [comment]
> @CalebUAz - not fixed until the config files are in the repo :)

Oh right!

**Comment by rchamplin** [comment]
Now that I have had a chance to test the configuration, I will take care of it.
Rick

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Adarsh Pyarelal ***@***.***>
Sent: Friday, September 2, 2022 1:20:04 PM
To: ml4ai/tomcat ***@***.***>
Cc: Champlin, Rick - (rchamplin) ***@***.***>; Comment ***@***.***>
Subject: [EXT]Re: [ml4ai/tomcat] Configuration files for LSL LabRecorder (Issue #294)


External Email

@CalebUAz<https://github.com/CalebUAz> - not fixed until the config files are in the repo :)
